export function getRandomElement<T>(arr: T[]): T {
    const randomIndex = Math.floor(Math.random() * arr.length);
    return arr[randomIndex];
}

export const listFirstName = [
    'Nguyễn',
    'Trần',
    'Lê',
    'Phạm',
    'Hoàng',
    'Phan',
    'Vũ',
    'Đặng',
    'Bùi',
    'Đỗ',
    'Hồ',
    'Ngô',
    'Dương',
    'Lý',
    'Huỳnh',
    'Võ',
];
export const listMiddleNameVn = [
    'Diệu',
    'Quỳnh',
    'Trâm',
    'Nguyệt',
    'Trân',
    'Quế',
    'Trúc',
    'Xuyến',
    'Thiên',
    'Ngọc',
    'Nghi',
    'Linh',
    'Thục',
    'Thu',
    'Thiên',
    'Hiếu',
    'Thái',
    'Dạ',
    'Quỳnh',
    'Thiên',
    'Ái',
    'Kim',
    'Vân',
    'Hồng',
    'Minh',
    'Diễm',
    'Chi',
    'Bạch',
    'Ngọc',
    'Mộc',
    'Ha',
    'Thương',
    'Dại',
    'Thu',
    'Uyển',
    'Yến',
    'Thục',
    'Hạnh',
    'Thanh',
    'Tú',
    'Song',
    'Cát',
    'Lâm',
    'Hương',
    'Dạ',
    'Anh',
    'Đoan',
    'Phượng',
    'Tịnh',
    'Hải',
    'Thiên',
    'Gia',
    'Thành',
    'Trung',
    'Thái',
    'Hải',
    'Thành',
    'Thông',
    'Phúc',
    'Tài',
    'Mạnh',
    'Chấn',
    'Bảo',
    'Khang',
    'Đăng',
    'Tuấn',
    'Thanh',
    'Hiền',
    'Thiện',
    'Thụ',
    'Minh',
    'Nhân',
    'Trọng',
    'Trung',
    'Khôi',
    'Hạo',
    'Phương',
    'Thanh',
    'Hữu',
    'Minh',
    'Đông',
    'Sơn',
    'Tùng',
    'Ái',
    'Thái',
    'Trường',
    'Thiện',
    'Thạch',
    'An',
    'Anh',
    'Thanh',
    'Chiến',
    'Toàn',
    'Minh',
    'Đình',
    'Kiến',
    'Nhân',
    'Khôi',
    'Quang',
    'Uy',
    'Hoài',
    'Huyền',
    'Thùy',
    'Trung',
    'Tú',
    'Vàng',
    'Hạ',
    'Lệ',
    'Tuyết',
    'Yên',
    'Ngọc',
    'Bảo',
    'Khải',
    'Sơn',
    'Nguyệt',
    'Bảo',
    'Ly',
    'Minh',
    'Hương',
    'Lan',
    'Lien',
    'Linh',
    'Mai',
    'Quỳnh',
    'Hiền',
    'Hạc',
    'Nhật',
    'Quỳnh',
    'Huyền',
    'Kỳ',
    'Vinh',
    'Thụy',
    'Van',
    'Hạnh',
    'Kiều',
    'Từ',
    'Thien',
    'Hải',
    'Hướng',
    'Thuy',
    'Kim',
    'Minh',
    'Yen',
    'Truc',
    'Hồng',
    'Hạ',
    'Hồng',
    'Hương',
    'Khánh',
];
export const listLastNameVn = [
    'Anh',
    'Cát',
    'Châu',
    'Chi',
    'Di',
    'Diệp',
    'Dung',
    'Đan',
    'Đoan',
    'Giang',
    'Hà',
    'Hạnh',
    'Hòa',
    'Hương',
    'Khanh',
    'Khánh',
    'Khuê',
    'Khue',
    'Kiều',
    'Lan',
    'Lien',
    'Mien',
    'Mi',
    'Nga',
    'Ngọc',
    'Nguyệt',
    'Nhã',
    'Oanh',
    'Quyên',
    'San',
    'Tâm',
    'Thư',
    'Tường',
    'Tuyền',
    'Thảo',
    'Thi',
    'Trang',
    'Vũ',
    'Yên',
    'Yến',
    'Ân',
    'Bảo',
    'Công',
    'Dũng',
    'Dương',
    'Đăng',
    'Đạt',
    'Điền',
    'Đức',
    'Hùng',
    'Hưng',
    'Kiện',
    'Khoa',
    'Kiệt',
    'Liêm',
    'Minh',
    'Ngôn',
    'Nhân',
    'Nhật',
    'Nghĩa',
    'Nguyên',
    'Nhiên',
    'Phi',
    'Phong',
    'Phước',
    'Quân',
    'Quốc',
    'Sơn',
    'Tùng',
    'Thái',
    'Thế',
    'Thắng',
    'Triết',
    'Trung',
    'Văn',
    'Vĩ',
    'Vinh',
    'An',
    'Băng',
    'Bằng',
    'Bích',
    'Bình',
    'Ca',
    'Chau',
    'Chung',
    'Cuc',
    'Dạ',
    'Dao',
    'Diệu',
    'Du',
    'Duyen',
    'Dan',
    'Dang',
];

export const khenSanPhamThuoc = [
    'Sản phẩm giúp tôi cảm thấy khỏe mạnh hơn mỗi ngày.',
    'Thuốc rất hiệu quả, tôi đã cải thiện sức khỏe rõ rệt.',
    'Đã sử dụng sản phẩm này và thấy sức khỏe tiến triển tích cực.',
    'Thuốc này giúp tôi giảm bớt cơn đau nhanh chóng.',
    'Tôi rất hài lòng với hiệu quả của sản phẩm này.',
    'Sản phẩm rất dễ sử dụng và mang lại hiệu quả như mong đợi.',
    'Thuốc có tác dụng nhanh và an toàn cho sức khỏe.',
    'Sau khi dùng thuốc, tôi cảm thấy sức khỏe cải thiện rõ rệt.',
    'Thuốc này không chỉ hiệu quả mà còn rất tiện lợi khi sử dụng.',
    'Tôi rất tin tưởng vào sản phẩm này và sẽ tiếp tục sử dụng.',
    'Sản phẩm giúp tôi vượt qua cơn bệnh nhanh chóng và dễ dàng.',
    'Thuốc giúp tôi có thể tiếp tục công việc mà không bị ảnh hưởng sức khỏe.',
    'Sản phẩm rất an toàn và phù hợp với nhu cầu sức khỏe của tôi.',
    'Tôi đã thử nhiều loại thuốc, nhưng sản phẩm này là tốt nhất.',
    'Sau khi sử dụng, tôi cảm thấy cơ thể nhẹ nhàng và dễ chịu hơn.',
    'Thuốc này thực sự hiệu quả, tôi đã cảm nhận được sự thay đổi rõ rệt.',
    'Sản phẩm giúp tôi cải thiện sức khỏe một cách nhanh chóng và hiệu quả.',
    'Thuốc có tác dụng lâu dài và giúp duy trì sức khỏe tốt.',
    'Tôi cảm thấy khỏe mạnh hơn và không còn lo lắng về vấn đề sức khỏe.',
    'Sản phẩm này là giải pháp tuyệt vời cho sức khỏe của tôi.',
];

export const randomReview = `${getRandomElement(khenSanPhamThuoc)}`;
export const randomName = `${getRandomElement(listFirstName)} ${getRandomElement(listMiddleNameVn)} ${getRandomElement(listLastNameVn)}`;
